version: '3.8'

services:
  fastapi-backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    command: uvicorn backend.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/fastapi
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
