[server]
# This should be set to the URL of your frontend server.
allowed_origins = ["http://localhost:3000"]

[datastores.sqlalchemy]
# Local SQLite: sqlite:///./sql_app.
# Postgresql: postgresql://user:password@postgresserver/db
database_url = "sqlite:///./sql_app.db"

[auth]
# Secret key for the Session middleware and JWT signing.
# WARNING: Do not use these in production, set them to random values!
secret_session_key = "change this to a randomized string"
secret_jwt_key = "change this to a randomized string"

[auth.google]
# Google OAuth authentication. You need to create credentials in a Google Cloud project:
# https://developers.google.com/workspace/guides/create-credentials#oauth-client-id
client_id = ""
client_secret = ""

[llms.ollama]
# Ollama - Local LLM
# Instructions: https://ollama.ai/
name = "ollama"
display_name = "Ollama"
model = "gemma:7b"
enabled = false
server_url = "http://localhost:11434"

[llms.vertexai]
# VertexAI - Google Cloud
# Set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the
# JSON file that contains your credentials. This variable applies only to your
# current shell session, so if you open a new session, set the variable again.
# Instructions: https://cloud.google.com/docs/authentication/provide-credentials-adc
name = "vertexai"
display_name = "VertexAI"
model = "gemini-1.0-pro-001"
enabled = false
project_name = ""  # GCP project for billing
